name: My Actions Demo
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  Explore-My-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
